# Generated by Django 5.2.1 on 2025-09-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chococroco', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
