# Generated by Django 5.2.1 on 2025-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chococroco', '0006_order_other_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
